### PR TITLE
Prettier Intergation

### PR DESCRIPTION
**Pull request by Bashamega**
#### Description

Please include a brief summary of the change and include the relevant issue(s).

#11 part 1

#### What change does this PR introduce?

Please select the relevant option(s).

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] CI/CD (updates related to the CI/CD process)
- [ ] Documentation update (changes to docs/code comments)
- [ ] Chore (miscellaneous tasks that do not fall into the above options)

#### What is the proposed approach?

Please give a short overview/explanation on the approach taken to resolve the issue(s).

#### Checklist:

- [x] The commit message follows our adopted [guidelines](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Testing has been done for the change(s) added (for bug fixes/features)
- [x] Relevant comments/docs have been added/updated (for bug fixes/features)

### CODE REVIEW

**Comment by PhuongHoang** [comment]
I am a bit confused and wonder if this PR is the same as #11? It looks like it has the same changes as #11.

**Comment by PhuongHoang** [comment]
> > I am a bit confused and wonder if this PR is the same as #11? It looks like it has the same changes as #11.
> 
> It is not the same pr.
> 
> This one is for prettier integration.

Ah I see. I think I didn't communicate very well on #11. I would love to have 2 separate PRs

1. A PR that contains *only* configurations for eslint and prettier, e.g. `eslint.js`, `.prettierrc` 
2. A PR that contains the files changed because of applying eslint and prettier

It makes the first PR very small and makes it simple to review the `real` changes closely. The second PR can be glanced quickly since it does not contain any logical changes. 

Please let me know if it can be done quickly that way. If it takes you a lot of time, I can review this PR. But for eslint, please follow the above suggestion.

**Comment by Bashamega** [comment]
Sure

**Comment by PhuongHoang** [comment]
> # I am very sorry, but I can't contribute to this project anymore

Oh no, I am very sorry to hear that. It is unfortunate that you are not able to contribute.

**Pull request closed without merging**
